r-place:
  world: rPlace
  min-x: -1000
  min-z: -1000
  max-x: 1000
  max-z: 1000
  build-y: 30
  delay-groups:
    default: 300
    vip: 150
    admin: 10
    owner: 0

messages:
  r-place:
    out-of-bounds: "&cYou are out of bounds!"
    still-timer: "&cYou have {seconds} seconds left before you can place another block!"
