r-place:
  world: rPlace
  min-x: -1000
  min-z: -1000
  max-x: 1000
  max-z: 1000
  build-y: -60
  delay: 300 #in seconds
  hotbar:
    enabled: false
    blocks:
      - WHITE_CONCRETE
      - RED_CONCRETE

messages:
  r-place:
    out-of-bounds: "&cYou are out of bounds!"
    still-timer: "&cYou have {seconds} seconds left before you can place another block!"
