name: SGCraftCreative
version: '${project.version}'
main: xyz.destiall.sgcraftcreative.SGCraftCreative
api-version: 1.18
depend:
  - PlotSquared
  - dynmap
loadbefore:
  - Multiverse-Core
commands:
  sgcraftcreative:
    description: SGCraft Creative
    permission: sgcraft.admin
